// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/puttsk/go-slurm/cli (interfaces: SacctMgrCLIHander)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSacctMgrCLIHander is a mock of SacctMgrCLIHander interface.
type MockSacctMgrCLIHander struct {
	ctrl     *gomock.Controller
	recorder *MockSacctMgrCLIHanderMockRecorder
}

// MockSacctMgrCLIHanderMockRecorder is the mock recorder for MockSacctMgrCLIHander.
type MockSacctMgrCLIHanderMockRecorder struct {
	mock *MockSacctMgrCLIHander
}

// NewMockSacctMgrCLIHander creates a new mock instance.
func NewMockSacctMgrCLIHander(ctrl *gomock.Controller) *MockSacctMgrCLIHander {
	mock := &MockSacctMgrCLIHander{ctrl: ctrl}
	mock.recorder = &MockSacctMgrCLIHanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSacctMgrCLIHander) EXPECT() *MockSacctMgrCLIHanderMockRecorder {
	return m.recorder
}

// ListQOS mocks base method.
func (m *MockSacctMgrCLIHander) ListQOS() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQOS")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQOS indicates an expected call of ListQOS.
func (mr *MockSacctMgrCLIHanderMockRecorder) ListQOS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQOS", reflect.TypeOf((*MockSacctMgrCLIHander)(nil).ListQOS))
}

// ListUser mocks base method.
func (m *MockSacctMgrCLIHander) ListUser() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUser")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUser indicates an expected call of ListUser.
func (mr *MockSacctMgrCLIHanderMockRecorder) ListUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUser", reflect.TypeOf((*MockSacctMgrCLIHander)(nil).ListUser))
}
